### PR TITLE
Update target version and describe input parameters in the readme

### PR DESCRIPTION
**Pull request by rwx788**

### CODE REVIEW

**Comment by siriak** [comment]
Good job! Can we update things to .NET 5? I'm getting those warnings
```
/usr/share/dotnet/sdk/5.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. 
```

**Comment by rwx788** [comment]
> Good job! Can we update things to .NET 5? I'm getting those warnings
> 
> ```
> /usr/share/dotnet/sdk/5.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. 
> ```

It won't harm, my only motivation was that .net 3.1 has LTS. But dotnet 5 sounds like a good idea to me!

**Comment by siriak** [comment]
What about the projects it generates? Are they .net 5 too?

**Comment by rwx788** [comment]
As of now generation part is hardcoded to `netstandard2.0` projects. There are some further improvements we might want to include in this tool. As of now it also misses entry point and generates a lot of warnings when is built.

**Comment by siriak** [comment]
I see, there are a lot of compile-time warnings indeed.

**Review by siriak — APPROVED** [review]

**Pull request merged**
